#libraries
wget https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar
wget http://central.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
#change folder
cd ..
cd src
cd ija
cd textures
#textures_general
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/background.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/card_back.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/empty.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/hint.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/icon.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/reassemble.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/selected.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/small_hint.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/small_selected.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/win.png
#textures_clubs
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C1.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C2.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C3.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C4.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C5.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C6.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C7.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C8.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C9.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C10.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C11.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C12.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/C13.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/Cempty.png
#textures_diamonds
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D1.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D2.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D3.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D4.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D5.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D6.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D7.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D8.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D9.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D10.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D11.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D12.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/D13.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/Dempty.png
#textures_hearts
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H1.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H2.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H3.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H4.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H5.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H6.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H7.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H8.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H9.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H10.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H11.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H12.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/H13.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/Hempty.png
#textures_spades
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S1.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S2.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S3.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S4.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S5.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S6.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S7.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S8.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S9.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S10.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S11.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S12.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/S13.png
wget http://eva.fit.vutbr.cz/~xbucha02/ija/textures/Sempty.png
#change folder
cd ..
cd music
#music
wget http://eva.fit.vutbr.cz/~xbucha02/ija/music/m1.wav
wget http://eva.fit.vutbr.cz/~xbucha02/ija/music/m2.wav
wget http://eva.fit.vutbr.cz/~xbucha02/ija/music/m3.wav
